#if defined(__MINGW32__) || defined(__CYGWIN__)
#define __DLL_IMPORT(name) (*__imp_##name)
#else
#define __DLL_IMPORT(name) (*name)
#endif

#define expand_names __DLL_IMPORT(expand_names)
#define ctab __DLL_IMPORT(ctab)
#define Klog __DLL_IMPORT(Klog)
#define Ktext __DLL_IMPORT(Ktext)
#define ciklog __DLL_IMPORT(ciklog)
#define RCS_version_string __DLL_IMPORT(RCS_version_string)
#define finptr __DLL_IMPORT(finptr)
#define foutptr __DLL_IMPORT(foutptr)
#define frewrite __DLL_IMPORT(frewrite)
#define nerror __DLL_IMPORT(nerror)
#define nextc __DLL_IMPORT(nextc)
#define quietflag __DLL_IMPORT(quietflag)
#define rcsline __DLL_IMPORT(rcsline)
#define AccessList __DLL_IMPORT(AccessList)
#define Comment __DLL_IMPORT(Comment)
#define Dbranch __DLL_IMPORT(Dbranch)
#define Expand __DLL_IMPORT(Expand)
#define Head __DLL_IMPORT(Head)
#define Locks __DLL_IMPORT(Locks)
#define StrictLocks __DLL_IMPORT(StrictLocks)
#define Symbols __DLL_IMPORT(Symbols)
#define TotalDeltas __DLL_IMPORT(TotalDeltas)
#define curlogbuf __DLL_IMPORT(curlogbuf)
#define interactiveflag __DLL_IMPORT(interactiveflag)
#define fcopy __DLL_IMPORT(fcopy)
#define locker_expansion __DLL_IMPORT(locker_expansion)
#define resultname __DLL_IMPORT(resultname)
#define RCSversion __DLL_IMPORT(RCSversion)
#define RCSname __DLL_IMPORT(RCSname)
#define RCSstat __DLL_IMPORT(RCSstat)
#define suffixes __DLL_IMPORT(suffixes)
#define workname __DLL_IMPORT(workname)
#define workstdout __DLL_IMPORT(workstdout)
#define prevauthor __DLL_IMPORT(prevauthor)
#define prevdate __DLL_IMPORT(prevdate)
#define prevname __DLL_IMPORT(prevname)
#define prevrev __DLL_IMPORT(prevrev)
#define prevstate __DLL_IMPORT(prevstate)
